# Generated by Django 2.0.2 on 2018-02-23 13:43

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('ttps', '0001_initial'),
        ('events', '0002_auto_20180222_1435'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventTTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
        migrations.AddField(
            model_name='eventttp',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttp_ev', to='events.Event'),
        ),
        migrations.AddField(
            model_name='eventttp',
            name='ttp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_ttp', to='ttps.TTP'),
        ),
    ]
