# Generated by Django 2.0.2 on 2018-02-23 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20180223_1546'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
    ]
