# Generated by Django 2.0.2 on 2018-02-23 22:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20180223_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventtype',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.EventType'),
        ),
    ]
