# Generated by Django 2.0.2 on 2018-02-24 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_auto_20180223_2245'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EventType',
            new_name='Type',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_type',
            new_name='type',
        ),
    ]
