# Generated by Django 2.0.2 on 2018-03-07 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20180306_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='eventdocument',
            name='title',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
