# Generated by Django 2.0.2 on 2018-03-07 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20180307_0932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventobservable',
            name='event',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='eventobservable',
            name='observable',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='observables.Observable'),
        ),
    ]
