# Generated by Django 2.0.2 on 2018-03-07 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20180307_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='targeted_organization',
        ),
    ]
