# Generated by Django 2.0.2 on 2018-03-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_auto_20180316_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reference',
            name='reference',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
