# Generated by Django 2.0.2 on 2018-03-19 10:16

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_auto_20180316_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='tag',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
