# Generated by Django 2.0.2 on 2018-03-21 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_auto_20180319_1024'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventcomment',
            name='author',
        ),
        migrations.RemoveField(
            model_name='eventcomment',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventComment',
        ),
    ]
