# Generated by Django 2.0.2 on 2018-03-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ttps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttp',
            name='ttp_type',
        ),
        migrations.AddField(
            model_name='ttp',
            name='ttp_type',
            field=models.ManyToManyField(blank=True, to='ttps.TTPType'),
        ),
    ]
