# Generated by Django 2.0.2 on 2018-02-19 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sector',
            name='is_nis',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sector',
            name='status',
            field=models.CharField(choices=[('critical', 'critical'), ('high', 'high'), ('medium', 'medium'), ('low', 'low'), ('unknown', 'unknown')], default='draft', max_length=10),
        ),
    ]
