# Generated by Django 2.0.2 on 2018-02-19 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_auto_20180219_1005'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sector',
            old_name='is_nis',
            new_name='constituent',
        ),
        migrations.AddField(
            model_name='sector',
            name='nis',
            field=models.BooleanField(default=True),
        ),
    ]
