# Generated by Django 2.0.2 on 2018-02-19 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20180219_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='constituent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sector',
            name='nis',
            field=models.BooleanField(default=False),
        ),
    ]
