# Generated by Django 2.0.2 on 2018-02-19 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('common', '0004_auto_20180219_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectorClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector_class', to='users.Account')),
            ],
        ),
        migrations.AddField(
            model_name='sector',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sector', to='users.Account'),
        ),
        migrations.AddField(
            model_name='sector',
            name='sector_class',
            field=models.ManyToManyField(related_name='sector', to='common.SectorClass'),
        ),
    ]
