# Generated by Django 2.0.2 on 2018-03-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20180219_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectorclass',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
