# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('necti', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to=b'documents/events/'),
        ),
    ]
