# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 11:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necti', '0002_auto_20180126_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
    ]
