# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 11:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necti', '0003_auto_20180126_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
        migrations.AlterField(
            model_name='threatactor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
        migrations.AlterField(
            model_name='threatactoralias',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
        migrations.AlterField(
            model_name='ttp',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Account'),
        ),
    ]
