# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necti', '0004_auto_20180126_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_author', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='event',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_author', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='incident',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incident_author', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='observable',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable_author', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='threatactor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_actor_author', to='users.Account'),
        ),
        migrations.AlterField(
            model_name='threatactoralias',
            name='author',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='necti.Subject'),
        ),
        migrations.AlterField(
            model_name='ttp',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttp_author', to='users.Account'),
        ),
    ]
