# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 11:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necti', '0005_auto_20180126_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threatactoralias',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='necti.Subject'),
        ),
    ]
