# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('necti', '0006_auto_20180126_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventComment',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='necti.Comment')),
            ],
            bases=('necti.comment',),
        ),
        migrations.AlterField(
            model_name='event',
            name='confidence',
            field=models.CharField(choices=[(b'critical', b'critical'), (b'high', b'high'), (b'medium', b'medium'), (b'low', b'low'), (b'unknown', b'unknown')], default=b'unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='event',
            name='risk',
            field=models.CharField(choices=[(b'critical', b'critical'), (b'high', b'high'), (b'medium', b'medium'), (b'low', b'low'), (b'unknown', b'unknown')], default=b'unknown', max_length=10),
        ),
        migrations.AddField(
            model_name='eventcomment',
            name='comments',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_comments', to='necti.Event'),
        ),
    ]
