# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2018-01-26 14:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('necti', '0007_auto_20180126_1338'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventcomment',
            old_name='comments',
            new_name='event',
        ),
    ]
