# Generated by Django 2.0.2 on 2018-02-16 12:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FileField(blank=True, upload_to='documents/observables/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='IpValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.GenericIPAddressField(blank=True, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Observable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=250, null=True, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('expiration_date', models.DateTimeField(blank=True, null=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('blacklist', models.BooleanField(default=False)),
                ('malware_eradication', models.BooleanField(default=False)),
                ('vurnerability_management', models.BooleanField(default=False)),
                ('to_ids', models.NullBooleanField(default=None)),
                ('sharing', models.BooleanField(default=True)),
                ('rateing', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable_author', to='users.Account')),
                ('kill_chain', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_kill_chain', to='common.KillChain')),
            ],
        ),
        migrations.CreateModel(
            name='ObservableType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('description', models.TextField(blank=True, null=True)),
                ('type_class', models.CharField(choices=[('ip_type', 'IP'), ('string_type', 'String'), ('email_type', 'Email'), ('file_type', 'File')], default=None, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='ObservableValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_values', to='observables.EmailValue')),
                ('ip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_values', to='observables.IpValue')),
                ('observable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='observables.Observable')),
            ],
        ),
        migrations.CreateModel(
            name='StringValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=25, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='observablevalues',
            name='string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_values', to='observables.StringValue'),
        ),
        migrations.AddField(
            model_name='observablevalues',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable_value', to='observables.ObservableType'),
        ),
        migrations.AddField(
            model_name='filevalue',
            name='file_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_value', to='observables.Observable'),
        ),
        migrations.AddField(
            model_name='filevalue',
            name='str_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_value', to='observables.ObservableType'),
        ),
    ]
