# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filevalue',
            old_name='value',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='ipvalue',
            old_name='value',
            new_name='ip',
        ),
        migrations.RenameField(
            model_name='stringvalue',
            old_name='value',
            new_name='string',
        ),
        migrations.RemoveField(
            model_name='emailvalue',
            name='value',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='email_value',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='file_value',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='ip_value',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='string_value',
        ),
        migrations.AddField(
            model_name='emailvalue',
            name='email',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='emailvalue',
            name='observable',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.Observable'),
        ),
        migrations.AddField(
            model_name='filevalue',
            name='observable',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.Observable'),
        ),
        migrations.AddField(
            model_name='ipvalue',
            name='observable',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.Observable'),
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='observable',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.Observable'),
        ),
        migrations.AlterField(
            model_name='observabletype',
            name='type_class',
            field=models.CharField(choices=[(b'ip_type', b'IP'), (b'string_type', b'String'), (b'email_type', b'Email'), (b'file_type', b'File')], default=b'string', max_length=10),
        ),
    ]
