# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0002_auto_20180205_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalue',
            name='observable',
        ),
        migrations.RemoveField(
            model_name='filevalue',
            name='observable',
        ),
        migrations.RemoveField(
            model_name='ipvalue',
            name='observable',
        ),
        migrations.RemoveField(
            model_name='stringvalue',
            name='observable',
        ),
        migrations.AddField(
            model_name='emailvalue',
            name='value',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AddField(
            model_name='filevalue',
            name='value',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AddField(
            model_name='ipvalue',
            name='value',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='value',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
    ]
