# Generated by Django 2.0.2 on 2018-02-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0002_auto_20180227_1340'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ObservableValues',
            new_name='ObservableValue',
        ),
    ]
