# Generated by Django 2.0.2 on 2018-03-01 11:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0003_auto_20180227_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalue',
            name='rateing',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='emailvalue',
            name='to_ids',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='ipvalue',
            name='rateing',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='ipvalue',
            name='to_ids',
            field=models.NullBooleanField(default=None),
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='rateing',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='to_ids',
            field=models.NullBooleanField(default=None),
        ),
    ]
