# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 16:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0003_auto_20180205_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalue',
            name='email',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AlterField(
            model_name='emailvalue',
            name='value',
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='filevalue',
            name='file',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AlterField(
            model_name='filevalue',
            name='value',
            field=models.FileField(upload_to=b'documents/observables/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='ipvalue',
            name='ip',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AlterField(
            model_name='ipvalue',
            name='value',
            field=models.GenericIPAddressField(),
        ),
        migrations.AlterField(
            model_name='stringvalue',
            name='string',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AlterField(
            model_name='stringvalue',
            name='value',
            field=models.CharField(max_length=25),
        ),
    ]
