# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 16:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0004_auto_20180205_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalue',
            name='email',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AlterField(
            model_name='filevalue',
            name='file',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AlterField(
            model_name='ipvalue',
            name='ip',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
        migrations.AlterField(
            model_name='stringvalue',
            name='string',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='observables.ObservableValue'),
        ),
    ]
