# Generated by Django 2.0.2 on 2018-03-02 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0006_auto_20180301_1505'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observablevalue',
            unique_together={('type', 'string'), ('observable', 'email'), ('observable', 'ip'), ('type', 'ip'), ('type', 'email'), ('observable', 'string')},
        ),
    ]
