# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 17:21
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0006_observablevalue_value_md5'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='observablevalue',
            managers=[
                ('types', django.db.models.manager.Manager()),
            ],
        ),
    ]
