# Generated by Django 2.0.2 on 2018-03-02 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0007_auto_20180302_1134'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observablevalue',
            unique_together={('observable', 'string'), ('observable', 'email'), ('observable', 'ip')},
        ),
    ]
