# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0009_observablevalue_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipvalue',
            name='value',
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
