# Generated by Django 2.0.2 on 2018-03-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0009_auto_20180302_1219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observable',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observable',
            name='first_seen',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='observable',
            name='last_seen',
            field=models.DateField(blank=True, null=True),
        ),
    ]
