# Generated by Django 2.0.2 on 2018-03-02 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0010_auto_20180302_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observablevalue',
            name='observable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='values', to='observables.Observable'),
        ),
    ]
