# Generated by Django 2.0.2 on 2018-03-04 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0010_auto_20180303_1246'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='observablevalue',
            unique_together=set(),
        ),
    ]
