# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 11:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0010_auto_20180206_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipvalue',
            name='ip',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_value', to='observables.ObservableValue'),
        ),
    ]
