# Generated by Django 2.0.2 on 2018-03-04 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0011_auto_20180304_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observablevalue',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_values', to='observables.EmailValue'),
        ),
        migrations.AlterField(
            model_name='observablevalue',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_values', to='observables.IpValue'),
        ),
        migrations.AlterField(
            model_name='observablevalue',
            name='observable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='observables.Observable'),
        ),
        migrations.AlterField(
            model_name='observablevalue',
            name='string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_values', to='observables.StringValue'),
        ),
    ]
