# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0011_auto_20180206_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpValueSelect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obsip_value', to='observables.ObservableValue')),
            ],
        ),
        migrations.RemoveField(
            model_name='ipvalue',
            name='ip',
        ),
        migrations.AddField(
            model_name='ipvalueselect',
            name='value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipvalue_value', to='observables.IpValue'),
        ),
    ]
