# Generated by Django 2.0.2 on 2018-03-13 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0012_auto_20180304_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observablevalue',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='observables.EmailValue'),
        ),
        migrations.AlterField(
            model_name='observablevalue',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='observables.IpValue'),
        ),
        migrations.AlterField(
            model_name='observablevalue',
            name='string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='observables.StringValue'),
        ),
        migrations.AlterField(
            model_name='observablevalue',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='values', to='observables.ObservableType'),
        ),
    ]
