# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-06 13:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0014_observablevalue__my_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalue',
            name='email',
        ),
        migrations.RemoveField(
            model_name='filevalue',
            name='file',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='_my_date',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='_value',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='value_md5',
        ),
        migrations.RemoveField(
            model_name='stringvalue',
            name='string',
        ),
    ]
