# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0015_auto_20180206_1357'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='observablevalue',
            managers=[
            ],
        ),
    ]
