# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 15:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0019_auto_20180208_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observablevalue',
            name='observable',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_values', to='observables.Observable'),
        ),
    ]
