# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0020_auto_20180208_1551'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observablevalue',
            name='ip_value',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='obs_type',
        ),
        migrations.RemoveField(
            model_name='observablevalue',
            name='observable',
        ),
        migrations.AddField(
            model_name='ipvalue',
            name='ip_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_value', to='observables.Observable'),
        ),
        migrations.AddField(
            model_name='ipvalue',
            name='obs_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable', to='observables.ObservableType'),
        ),
        migrations.DeleteModel(
            name='ObservableValue',
        ),
    ]
