# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-08 17:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0021_auto_20180208_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailvalue',
            name='ip_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_value', to='observables.Observable'),
        ),
        migrations.AddField(
            model_name='emailvalue',
            name='str_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_value', to='observables.ObservableType'),
        ),
        migrations.AddField(
            model_name='filevalue',
            name='ip_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_value', to='observables.Observable'),
        ),
        migrations.AddField(
            model_name='filevalue',
            name='str_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='file_value', to='observables.ObservableType'),
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='ip_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='str_value', to='observables.Observable'),
        ),
        migrations.AddField(
            model_name='stringvalue',
            name='str_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='str_value', to='observables.ObservableType'),
        ),
        migrations.AlterField(
            model_name='ipvalue',
            name='obs_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_value', to='observables.ObservableType'),
        ),
    ]
