# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 10:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0023_auto_20180208_1749'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailvalue',
            old_name='ip_value',
            new_name='email_value',
        ),
        migrations.RenameField(
            model_name='filevalue',
            old_name='ip_value',
            new_name='file_value',
        ),
        migrations.RenameField(
            model_name='stringvalue',
            old_name='ip_value',
            new_name='str_value',
        ),
        migrations.AlterField(
            model_name='observabletype',
            name='type_class',
            field=models.CharField(choices=[(b'ip_type', b'IP'), (b'string_type', b'String'), (b'email_type', b'Email'), (b'file_type', b'File')], default=b'string_type', max_length=25),
        ),
    ]
