# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 12:07
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0024_auto_20180209_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observable',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
