# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0025_auto_20180209_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observable',
            name='name',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
