# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0027_auto_20180209_1217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvalue',
            name='value',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='filevalue',
            name='value',
            field=models.FileField(blank=True, upload_to=b'documents/observables/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='stringvalue',
            name='value',
            field=models.CharField(blank=True, max_length=25, unique=True),
        ),
    ]
