# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0029_auto_20180209_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observabletype',
            name='type_class',
            field=models.CharField(choices=[(b'ip_type', b'IP'), (b'string_type', b'String'), (b'email_type', b'Email'), (b'file_type', b'File')], default=None, max_length=25),
        ),
    ]
