# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 16:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_events', '0006_remove_event_observable'),
        ('observables', '0030_auto_20180209_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='observable',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable', to='cyber_events.Event'),
        ),
    ]
