# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 16:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0031_observable_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observable',
            name='event',
        ),
    ]
