# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 16:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('observables', '0032_remove_observable_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observable',
            name='kill_chain',
        ),
        migrations.AddField(
            model_name='observable',
            name='kill_chain',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='obs_kill_chain', to='common.KillChain'),
        ),
    ]
