# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 12:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0035_auto_20180215_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipvalue',
            name='ip_value',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_value', to='observables.Observable'),
        ),
    ]
