# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0036_auto_20180215_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipvalue',
            name='ip_value',
            field=models.ForeignKey(null=True, on_delete=models.SET(None), related_name='ip_value', to='observables.Observable'),
        ),
    ]
