# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 12:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0038_auto_20180215_1237'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObservableValues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observables.Observable')),
                ('value', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='observables.IpValue')),
            ],
        ),
    ]
