# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0040_auto_20180215_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='observablevalues',
            name='observable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ip_values', to='observables.Observable'),
        ),
        migrations.AlterField(
            model_name='observablevalues',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_values', to='observables.IpValue'),
        ),
    ]
