# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 13:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0041_auto_20180215_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='observablevalues',
            name='value',
        ),
    ]
