# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 13:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0043_observablevalues_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipvalue',
            name='ip_value',
        ),
    ]
