# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 13:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0045_auto_20180215_1329'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.GenericIPAddressField(blank=True, null=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ip_test', to='observables.ObservableType')),
            ],
        ),
        migrations.AlterField(
            model_name='observablevalues',
            name='value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_values', to='observables.Test'),
        ),
    ]
