# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 17:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0049_auto_20180215_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='type',
        ),
        migrations.AlterField(
            model_name='observablevalues',
            name='ip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_values', to='observables.IpValue'),
        ),
    ]
