# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0051_auto_20180215_1752'),
    ]

    operations = [
        migrations.AddField(
            model_name='observablevalues',
            name='email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_values', to='observables.EmailValue'),
        ),
    ]
