# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0052_observablevalues_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalue',
            name='email_value',
        ),
    ]
