# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0053_remove_emailvalue_email_value'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emailvalue',
            old_name='str_type',
            new_name='type',
        ),
    ]
