# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0054_auto_20180215_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailvalue',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ipvalue',
            name='type',
        ),
        migrations.AddField(
            model_name='observablevalues',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_value', to='observables.ObservableType'),
        ),
    ]
