# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0056_auto_20180215_2015'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Test',
        ),
    ]
