# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-15 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0057_delete_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stringvalue',
            name='str_type',
        ),
        migrations.RemoveField(
            model_name='stringvalue',
            name='str_value',
        ),
        migrations.AddField(
            model_name='observablevalues',
            name='string',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='obs_values', to='observables.StringValue'),
        ),
    ]
