# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 17:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
                ('reference', models.CharField(blank=True, max_length=250, null=True)),
                ('hunting', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('first_seen', models.DateTimeField(blank=True, null=True)),
                ('last_seen', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttp_author', to='users.Account')),
            ],
            options={
                'verbose_name': 'TTP',
                'verbose_name_plural': 'TTPs',
            },
        ),
        migrations.CreateModel(
            name='TTPCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TTP Category',
                'verbose_name_plural': 'TTP Categories',
            },
        ),
        migrations.CreateModel(
            name='TTPType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'TTP Type',
                'verbose_name_plural': 'TTP Types',
            },
        ),
        migrations.AddField(
            model_name='ttp',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttp_category', to='ttp.TTPCategory'),
        ),
        migrations.AddField(
            model_name='ttp',
            name='intention',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttp_intention', to='common.Intentsion'),
        ),
        migrations.AddField(
            model_name='ttp',
            name='kill_chain',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttp_kill_chain', to='common.KillChain'),
        ),
        migrations.AddField(
            model_name='ttp',
            name='ttp_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ttp_type', to='ttp.TTPType'),
        ),
    ]
