# Generated by Django 2.0.2 on 2018-02-16 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('ttps', '0001_initial'),
        ('users', '0001_initial'),
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='threatactorttp',
            name='ttp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_actor', to='ttps.TTP'),
        ),
        migrations.AddField(
            model_name='threatactor',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_actor_author', to='users.Account'),
        ),
        migrations.AddField(
            model_name='threatactor',
            name='motive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_actor_motive', to='common.Motive'),
        ),
        migrations.AddField(
            model_name='threatactor',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_actor_type', to='actors.ActorType'),
        ),
        migrations.AddField(
            model_name='organizationdomain',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization_domain', to='users.Account'),
        ),
        migrations.AddField(
            model_name='organization',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituent_author', to='users.Account'),
        ),
        migrations.AddField(
            model_name='organization',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='organization', to='actors.OrganizationDomain'),
        ),
        migrations.AddField(
            model_name='organization',
            name='type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='constituent_type', to='actors.ActorType'),
        ),
    ]
