# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 15:18
from __future__ import unicode_literals

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_threatactorttp'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='country',
            field=django_countries.fields.CountryField(blank=True, max_length=746, multiple=True),
        ),
    ]
