# Generated by Django 2.0.2 on 2018-03-07 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_remove_event_targeted_organization'),
        ('actors', '0003_auto_20180307_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='actor',
            name='actor',
            field=models.ManyToManyField(to='actors.Organization'),
        ),
        migrations.AddField(
            model_name='actor',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.Event'),
        ),
        migrations.AlterField(
            model_name='actor',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter'), ('target', 'Target'), ('threat_actor', 'Threat Actor'), ('unknown', 'unknown')], default='unknown', max_length=10),
        ),
    ]
