# Generated by Django 2.0.2 on 2018-03-07 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0004_auto_20180307_1536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actor',
            name='role',
            field=models.CharField(choices=[('reporter', 'Reporter'), ('target', 'Target'), ('threat_actor', 'Threat Actor'), ('unknown', 'unknown')], default='unknown', max_length=25),
        ),
    ]
