# Generated by Django 2.0.2 on 2018-03-12 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_auto_20180307_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actortype',
            name='name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
