# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0006_organizationdomain_risk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationdomain',
            name='country',
        ),
    ]
