# Generated by Django 2.0.2 on 2018-03-19 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0008_auto_20180312_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='alias',
            field=models.ManyToManyField(blank=True, related_name='_organization_alias_+', to='actors.Organization'),
        ),
    ]
