# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-09 22:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('cyber_events', '0003_remove_eventcomment_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventgeolocation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='eventmotive',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventmotive',
            name='motive',
        ),
        migrations.RemoveField(
            model_name='eventreporter',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventreporter',
            name='reporter',
        ),
        migrations.RemoveField(
            model_name='eventsector',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventsector',
            name='sector',
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='motive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_motive', to='common.Motive'),
        ),
        migrations.AddField(
            model_name='event',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_reporter', to='common.Reporter'),
        ),
        migrations.AddField(
            model_name='event',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ev_sector', to='common.Sector'),
        ),
        migrations.DeleteModel(
            name='EventGeoLocation',
        ),
        migrations.DeleteModel(
            name='EventMotive',
        ),
        migrations.DeleteModel(
            name='EventReporter',
        ),
        migrations.DeleteModel(
            name='EventSector',
        ),
    ]
