# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0030_auto_20180209_1426'),
        ('cyber_events', '0004_auto_20180209_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='observable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='observables.Observable'),
        ),
    ]
