# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_events', '0005_event_observable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='observable',
        ),
    ]
