# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-13 16:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('observables', '0032_remove_observable_event'),
        ('cyber_events', '0006_remove_event_observable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventObservable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='observable', to='cyber_events.Event')),
                ('observable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='observables.Observable')),
            ],
        ),
    ]
