# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 11:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0003_threatactorttp'),
        ('cyber_events', '0007_eventobservable'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventThreatActor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='threat_actor', to='cyber_events.Event')),
                ('threat_actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='actors.ThreatActor')),
            ],
        ),
    ]
