# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_events', '0008_eventthreatactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', django_countries.fields.CountryField(max_length=2, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
        migrations.AlterField(
            model_name='event',
            name='motive',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='common.Motive'),
        ),
        migrations.AlterField(
            model_name='event',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='common.Reporter'),
        ),
        migrations.AlterField(
            model_name='event',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='common.Sector'),
        ),
    ]
