# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_events', '0011_remove_event_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='cyber_events.EventCountry'),
        ),
    ]
