# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 13:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_events', '0012_event_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
        migrations.AddField(
            model_name='event',
            name='country',
            field=models.ManyToManyField(blank=True, related_name='event', to='cyber_events.EventCountry'),
        ),
    ]
