# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cyber_events', '0015_auto_20180214_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='country',
        ),
    ]
