# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('cyber_events', '0017_event_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='motive',
        ),
        migrations.AddField(
            model_name='event',
            name='motive',
            field=models.ManyToManyField(blank=True, related_name='event', to='common.Motive'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='reporter',
        ),
        migrations.AddField(
            model_name='event',
            name='reporter',
            field=models.ManyToManyField(blank=True, related_name='event', to='common.Reporter'),
        ),
        migrations.RemoveField(
            model_name='event',
            name='sector',
        ),
        migrations.AddField(
            model_name='event',
            name='sector',
            field=models.ManyToManyField(blank=True, related_name='event', to='common.Sector'),
        ),
    ]
